CREATE TABLE [dbo].[SubMenu]
(
	[Id] INT NOT NULL IDENTITY(1,1),
	[MenuId] INT NOT NULL,
	[Name] VARCHAR(50) NOT NULL,
	[Description] VARCHAR(100) NOT NULL,
	[Price] FLOAT NOT NULL,
	[Image] VARCHAR(MAX) NOT NULL,
	CONSTRAINT [PK_SUBMENU_ID] PRIMARY KEY CLUSTERED ([Id]),
	CONSTRAINT [FK_MENU_ID] FOREIGN KEY ([MenuId]) REFERENCES [Menu] ([Id])
)
